# This files contains all configuration options for analysis running.
# More details please refer to: https://golangci-lint.run/usage/configuration/

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # One of 'readonly' and 'vendor'.
  #  - readonly: the go command is disallowed from the implicit automatic updating of go.mod described above.
  #              Instead, it fails when any changes to go.mod are needed. This setting is most useful to check
  #              that go.mod does not need updates, such as in a continuous integration and testing system.
  #  - vendor: the go command assumes that the vendor directory holds the correct copies of dependencies and ignores
  #            the dependency descriptions in go.mod.
  modules-download-mode: readonly
linters:
  enable:
  # linters maintained by golang.org
  - gofmt
  - revive
  - govet
  # linters default enabled by golangci-lint .
  - errcheck
  - gosimple
  - ineffassign
  - staticcheck
  - typecheck
  - unused
# All available settings of specific linters.
linters-settings:
  gci:
    skip-generated: false
    custom-order: true
  gosec:
    severity: medium
    confidence: medium
  revive:
    enable-all-rules: true
    severity: warning
    rules:
      - name: var-naming
        disabled: false
        arguments:
          - ["API", "ID", "IDS", "IP", "VM", "JSON", "HTTP", "URL", "XML", "YAML", "CSS", "ACL", "CPU", "SQL", "EIP"] # AllowList
      - name: cognitive-complexity
        disabled: true
      - name: add-constant
        disabled: true
      - name: use-any
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cyclomatic
        severity: warning
        disabled: false
        exclude: [""]
        arguments: [5]
      - name: line-length-limit
        disabled: false
        arguments: [150]
      - name: cyclomatic
        disabled: false
        arguments: [15]
issues:
  # The list of ids of default excludes to include or disable. By default it's empty.
  include:
  # Which dirs to exclude: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path,
  # including the path prefix if one is set.
  # Default dirs are skipped independently of this option's value (see exclude-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  exclude-dirs:
    - pkg/apigw
    - pkg/cloudprovider/huaweicloud/model
    - pkg/cloudprovider/huaweicloud/wrapper/model
    - test
  # Which files to exclude: they will be analyzed, but issues from them won't be reported.
  # There is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not, please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  exclude-files:
    - pkg/cloudprovider/huaweicloud/elb.go
    - pkg/cloudprovider/huaweicloud/elb_connection.go
    - pkg/cloudprovider/huaweicloud/http.go
    - pkg/cloudprovider/huaweicloud/nat.go
    - pkg/cloudprovider/huaweicloud/nat_connections.go
    - pkg/cloudprovider/huaweicloud/throttle.go
    - pkg/utils/loggertripper.go
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - revive

