name: released image to SWR
on:
  release:
    types:
      - published
jobs:
  release-image:
    name: release images
    # prevent job running from forked repository, otherwise
    # 1. running on the forked repository would fail as missing necessary secret.
    # 2. running on the forked repository would use unnecessary GitHub Action time.
    if: ${{ github.repository == 'kubernetes-sigs/cloud-provider-huaweicloud' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '>=1.22'
      - name: build images
        env:
          REGISTRY: ${{secrets.SWR_REGISTRY}}
          REGISTRY_USER_NAME: ${{secrets.SWR_REGISTRY_USER_NAME}}
          REGISTRY_PASSWORD: ${{secrets.SWR_REGISTRY_PASSWORD}}
          REGISTRY_SERVER_ADDRESS: ${{secrets.SWR_REGISTRY_SERVER_ADDRESS}}
          VERSION: ${{ github.ref_name }}
        run: make upload-images
